# Generated by Django 5.1.4 on 2025-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='posting_state',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
