# Generated by Django 4.2.11 on 2025-04-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cause_of_illness',
        ),
    ]
