# Generated by Django 4.2.11 on 2025-04-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_remove_customer_cause_of_illness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='aadhar',
        ),
    ]
