# Generated by Django 5.1.4 on 2025-03-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_district_state_block_district_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
