# Generated by Django 4.2.11 on 2025-06-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_remove_customer_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_slip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='transaction_id',
        ),
    ]
