# Generated by Django 4.2.11 on 2025-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_remove_customer_payment_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Optional reference person name', max_length=100, null=True),
        ),
    ]
