# Generated by Django 5.1.4 on 2025-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_remove_notification_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
