# Generated by Django 4.2.11 on 2025-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_customer_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group (e.g., A+, B-, O+)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
