# Generated by Django 5.1.4 on 2025-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_notification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nominee_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_nominee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
