# Generated by Django 4.2.11 on 2025-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_customer_aadhar_customer_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a passport size photo for ID card', null=True, upload_to='id_cards/'),
        ),
    ]
