# Generated by Django 5.1.4 on 2025-03-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_remove_customer_nominee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='nominee_relation',
            new_name='first_nominee_relation',
        ),
    ]
