# Generated by Django 5.1.4 on 2025-03-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_rename_nominee_relation_customer_first_nominee_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nominee_mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_nominee_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_nominee_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
