# Generated by Django 5.1.4 on 2025-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_alter_customer_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='posting_block',
        ),
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='posting_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='posting_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
